# Generated by Django 4.1.2 on 2023-01-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_post_user_id_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
